
// Business Logic Constants matching the Legacy Dashboard

export const EXCLUDED_PRODUCTS_LIST = [
  'TW SHINER SPONGE',
  'CHAIN LUBE',
  'CHAIN CLEANER',
  'BRAKE CLEANER',
  'FUELINJECT',
  'ANTI RUST LUB SPRAY',
  'THROTTLEBODYCLEANER',
  'MICRO FBR CLOTH',
  'AIOHELMET CLEANER',
  'TW SHINER 3 IN 1'
];

export const POWER1_PRODUCTS_LIST = [
  "POWER1 4T 10W-30, 10X.9L MK",
  "POWER1 4T 10W-30, 10X1L MK",
  "POWER1 4T 15W-40, 10X1L MK",
  "POWER1 CRUISE4T 20W50 10X1.2HMK",
  "POWER1 CRUISE 4T20W-50,10X1L",
  "POWER1 ULTIMATE4T10W-40,6X1LMK",
  "POWER1CRUISE4T 15W50,4X2.5L MK"
];

export const ACTIV_BRANDS_INCLUDE = ['ACTIV'];
export const ACTIV_BRANDS_EXCLUDE = ['ACTIV ESSENTIAL'];

export const MAGNATEC_BRANDS_INCLUDE = [
    'MAGNATEC', 
    'MAGNTEC SUV', 
    'MAGNATEC DIESEL'
];

export const CRB_BRANDS_INCLUDE = ['CRB TURBOMAX'];

export const AUTOCARE_BRANDS_INCLUDE = [
  'AUTO CARE EXTERIOR',
  'AUTO CARE MAINTENANCE'
];

// Thresholds
export const THRESHOLD_ACTIV = 0.9;
export const THRESHOLD_POWER1 = 5;
export const THRESHOLD_MAGNATEC = 3.5;
export const THRESHOLD_CRB = 1;
export const THRESHOLD_AUTOCARE = 5;
export const THRESHOLD_CORE_UNBILLED = 9;
